### ISSUE TITLE
임시 페이지 수 정산 re

### ISSUE THREAD

**Issue by sby0126** [biud436/project_one#11]
# men, women + 내부 라디오 삭제 시

## main

- [x] shop 1
- [x] item 1
- [ ] sale 1 - 내부 페이지 로드 or page 3

## more - sub menu

- [ ] 관심 상품 1
- [ ] 관심 샵 1
- [ ] 장바구니 1
- [x] 게시판 1
- [x] 맵 + 약관 3

## extra - menu 상에서의 이동 x

- [x] 로그인 1
- [x] 회원가입 1
- [x] 아이디 / 패스워드 찾기 1 ? +a?
- [x] 해당 상품 ex 1
- [ ] 결제 1

총 : 15 ~17 +a

-----------------------------------------
# men, women 라디오 생존, 내부 라디오 삭제 시

## main
- [x] shop 2
- [ ] item 2
- [ ] sale 2 - 내부 페이지 로드 or page 6

## more - sub menu

- [ ] 관심 상품 1
- [ ] 관심 샵 1
- [ ] 장바구니 1
- [ ] 게시판 1
- [ ] 맵 + 약관 3

### extra - menu 상에서의 이동 x

- [x] 로그인 1
- [x] 회원가입 1
- [ ] 아이디 / 패스워드 찾기 1 ? +a?
- [ ] 해당 상품 ex 1
- [ ] 결제 1

총 : 18 ~ 22 +a

**Comment by sby0126** [comment]
이슈의 갱신 기능을 몰라서 원 이슈 닫고 재업했습니다. 
추가로 작성해야 될 페이지가 있을 경우 알려주시면 많은 도움이 될 듯 합니다.

**Comment by biud436** [comment]
tast lilst 추가
